name: Auto PR dev2main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions Bot"

      
      - name: Fetch All Branches and Ensure `main` & `dev` Exist
        run: |
          git fetch origin  # Ensure we fetch all remote branches
          
          # Create local tracking branches if they don't exist
          if ! git show-ref --verify --quiet refs/heads/main; then
            git branch main origin/main
          fi
          
          if ! git show-ref --verify --quiet refs/heads/dev; then
            git branch dev origin/dev
          fi

      - name: Check for Differences Between `dev` and `main`
        id: check_diff
        run: |
          DIFF=$(git diff --name-only main dev -- || true)

          if [[ -z "$DIFF" ]]; then
            echo "No differences detected. Exiting."
            exit 0
          fi
    
      - name: Debug - List Local and Remote Branches
        run: |
          git branch -a

      - name: Create Pull Request
        run: |
          gh pr create --base main --head dev \
            --title "Auto PR: Merge dev into main" \
            --body "This PR was automatically created for review." \
            --reviewer "abisatyaw" \
            --label "auto-pr"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
